export default {
    SET: 'SET',
    GET: 'GET',
    REMOVE_ITEM: 'REMOVE_ITEM',
    GET_MOVIE_BY_ID: 'GET_MOVIE_BY_ID',
    GET_ALL_KEYS: 'GET_ALL_KEYS',
    MULTI_SET: 'MULTI_SET',
    MULTI_REMOVE: 'MULTI_REMOVE',
    CLEAR_ALL: 'CLEAR_ALL',
}